language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.7"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  # - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #  else
  #    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #  fi
  #- chmod +x miniconda.sh
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  #- conda info -a
  #- conda env create --file test/test_env.yml
  #- source activate test_env

  -set -e

  -if [[ "$DISTRIB" == "conda" ]]; then
    # Deactivate the travis-provided virtual environment and setup a
    # conda-based environment instead
    deactivate

    # Use the miniconda installer for faster download / install of conda
    # itself
    DOWNLOAD_DIR=${DOWNLOAD_DIR:-$HOME/.tmp/miniconda}
    mkdir -p $DOWNLOAD_DIR
    wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh \
        -O $DOWNLOAD_DIR/miniconda.sh
    chmod +x $DOWNLOAD_DIR/miniconda.sh && \
        bash $DOWNLOAD_DIR/miniconda.sh -b -p $HOME/miniconda && \
        rm -r -d -f $DOWNLOAD_DIR
    export PATH=$HOME/miniconda/bin:$PATH
    conda update --yes conda

    # Configure the conda environment and put it in the path using the
    # provided versions
    conda create -n testenv --yes python=$PYTHON_VERSION pip
    source activate testenv
  elif [[ "$DISTRIB" == "ubuntu" ]]; then
    # Use standard ubuntu packages in their default version
    echo $DISTRIB
  fi

  -if [[ "$COVERAGE" == "true" ]]; then
    pip install coverage coveralls
   fi

script:
  - py.test --cov-config .coveragerc --cov=myproject3 test

after_success:
- codecov
